# Generated by Django 6.1.1 on 2026-10-08 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0002_review_payment_amount_payment_verified_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('FOOD', 'Pesan Makanan & Minuman'), ('AMENITIES', 'Request Amenities'), ('EXTRA_BED', 'Request Extra Bed'), ('LAUNDRY', 'Laundry'), ('RECEPTION', 'Chat dengan Resepsionis')], default='FOOD', max_length=20)),
                ('detail', models.TextField(blank=True, help_text='Contoh: Nasi Goreng x1, Mie Goreng x2')),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Diproses'), ('CONFIRMED', 'Dikonfirmasi'), ('DELIVERED', 'Diantar / Selesai'), ('CANCELLED', 'Dibatalkan')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to='reservations.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
