# Generated by Django 6.1.1 on 2026-10-01 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kode_voucher', models.CharField(max_length=50, unique=True)),
                ('persen_diskon', models.FloatField(default=0.0)),
                ('potongan_nominal', models.FloatField(default=0.0)),
                ('minimal_transaksi', models.FloatField(default=0.0)),
                ('tanggal_kedaluwarsa', models.DateTimeField()),
                ('kuota_penggunaan', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemporaryRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_kamar', models.CharField(max_length=10)),
                ('harga_per_malam', models.FloatField(default=500000.0)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tanggal_check_in', models.DateTimeField()),
                ('tanggal_check_out', models.DateTimeField()),
                ('jumlah_tamu', models.IntegerField(default=1)),
                ('total_harga_dasar', models.FloatField(default=0.0)),
                ('pajak_dan_layanan', models.FloatField(default=0.0)),
                ('total_biaya_akhir', models.FloatField(default=0.0)),
                ('status_pesanan', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Lunas'), ('CANCELLED', 'Dibatalkan')], default='PENDING', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.promovoucher')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.temporaryroom')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metode_pembayaran', models.CharField(max_length=50)),
                ('bukti_transfer_url', models.ImageField(blank=True, null=True, upload_to='bukti_transfer/')),
                ('status_pembayaran', models.CharField(choices=[('WAITING', 'Menunggu Verifikasi'), ('VERIFIED', 'Terverifikasi'), ('REJECTED', 'Ditolak')], default='WAITING', max_length=50)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='reservations.booking')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
