# Generated by Django 6.1.1 on 2026-10-01 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='jumlah_tamu',
            field=models.PositiveIntegerField(db_column='guest_count', default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pajak_dan_layanan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status_pesanan',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked-in'), ('CHECKED_OUT', 'Checked-out'), ('CANCELLED', 'Dibatalkan')], db_column='status', default='PENDING_PAYMENT', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tanggal_check_in',
            field=models.DateField(db_column='check_in_date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tanggal_check_out',
            field=models.DateField(db_column='check_out_date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_biaya_akhir',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_harga_dasar',
            field=models.DecimalField(db_column='total_amount', decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(db_column='guest_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bukti_transfer_url',
            field=models.ImageField(blank=True, db_column='proof', null=True, upload_to='bukti_transfer/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='metode_pembayaran',
            field=models.CharField(db_column='method', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status_pembayaran',
            field=models.CharField(choices=[('UNPAID', 'Belum Dibayar'), ('PENDING_VERIFICATION', 'Menunggu Verifikasi'), ('VERIFIED', 'Terverifikasi'), ('REJECTED', 'Ditolak')], db_column='status', default='UNPAID', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('tanggal_check_out__gt', models.F('tanggal_check_in'))), name='booking_checkout_after_checkin'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('jumlah_tamu__gt', 0)), name='booking_guest_count_positive'),
        ),
        migrations.AlterModelTable(
            name='booking',
            table='bookings',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payments',
        ),
        migrations.AddField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='reservations.booking'),
        ),
        migrations.AddField(
            model_name='review',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_1_to_5'),
        ),
    ]
