# Generated by Django 6.1.1 on 2026-10-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_seed_vouchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='tanggal_check_in',
            field=models.DateTimeField(db_column='check_in_date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tanggal_check_out',
            field=models.DateTimeField(db_column='check_out_date'),
        ),
    ]
