# Generated by Django 6.1.1 on 2026-10-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_booking_checked_in_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
