# Generated by Django 6.1.1 on 2026-10-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestprofile',
            name='role',
            field=models.CharField(choices=[('GUEST', 'Guest'), ('ADMIN', 'Admin')], default='GUEST', max_length=20),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20),
        ),
    ]
